### ISSUE TITLE
Why do PNGs take so long to optimize?

### ISSUE THREAD

**Issue by keirthomas** [ImageOptim/ImageOptim#140]
I've the fastest MacBook Pro you can get and it still takes around a minute to optimize a 100Kb PNG.

JPGs are done instantly!

**Comment by pornel** [comment]
The losslesss compression part of JPEG is simpler. 

JPEG just uses Huffman coding. 

PNG uses preprocessing filters × block splitting × backreferences × Huffman coding, which creates many many more combinations to explore.

In practice Zopfli and PNGOUT are very slow. You can disable them in Preferences, and you'll get faster optimization, but a bit larger files.

**Comment by denji** [comment]
Disabled Zopfli, speedup 300%

**Comment by pornel** [comment]
In the meantime Zopfli has got some nice speed upgrades.

**Comment by tomasdev** [comment]
still an issue in 2018 :p

**Comment by SpikyAlumnus** [comment]
What is faster? Fast or Insane? Is it insanely slow or fast?

**Comment by kornelski** [comment]
"Fast" is the fastest. The other option are slower. "Insane" means it will take hours or even days to optimize a file.

**Comment by AlecKinnear** [comment]
Anyone else who stops by here in 2023, changing the setting to Fast is the most important change.

With Zopfli turned off and Optimisation level dropped back from Extra to just Normal on an M1 Max, optimisation speed went from about 30 seconds to 2 or 3 seconds.

Does it make a difference in terms of size? No. Here's an image of all my tests which included various sets of preferences turned on/off, mostly done at extra level.

![ImageOptim-tests-various-levels](https://github.com/ImageOptim/ImageOptim/assets/107859958/e02e1b10-78eb-446c-aa5b-30159dadb6fb)

The last one test-image copy 6 was with Normal and with everything except Zopfli turned on. These tests were done with lossless PNG.

![ImageOptim-png-settings](https://github.com/ImageOptim/ImageOptim/assets/107859958/35975601-447e-42a6-ae4b-dcb4f3bbdc11)

Setting quality to 80% resulted in 72% space save, but seemed to take a second or two longer.

With these settings, ImageOptim is viable for PNG. Otherwise it was just waiting for minutes to optimise five or six files, disrupting workflow.

**Comment by stevencasteel** [comment]
Alec's advice shaved 2MB off of a 15MB file for me with no visual loss.

On an M1 8GB Mac mini.

The default settings wouldn't complete the file in 10 minutes.

New settings were less than 30 seconds.

Also, for anyone coming across this, JPEGmini Pro absolutely RIPS through thousands of files reducing them immensely with minute loss. I've been using it to compress my thousands of AI images.
