### ISSUE TITLE
Corrupt file when imported into Lightroom after using ImageOptim

### ISSUE THREAD

**Issue by virginie24jb** [ImageOptim/ImageOptim#146]
Hi,

I noticed that when I imported into Lightroom JPG files that had gone through ImageOptim, the file looks like a corrupt file.
Here's an example: instead of [this](https://www.flickr.com/photos/95412676@N07/15445643755/in/dateposted-public/), here's what the image looks like into Lightroom for me now after going through ImageOptim :

![capture d ecran 2016-06-12 a 11 08 08](https://cloud.githubusercontent.com/assets/19887460/15990244/fd21c3b8-308d-11e6-9d47-175a310ae966.png)

Is there an option in ImageOptim that I selected and that I shouldn't have?

**Comment by pornel** [comment]
Lightroom and Bridge don't support progressive JPEGs correctly. They use a custom, weak decoder. You may try filing a bug with Adobe to remind them about that.

There's no option in ImageOptim to avoid that, because the biggest savings depend on progressive decoding that Adobe is so bad at handling.

However, I suggest that you change your workflow. Saving image as JPEG is lossy, so it should be the final step in any workflow, and such image should not be fed back into any image editing tools. If you want to keep images editable, keep them in PNG, RAW, or one of Adobe's formats. Degrade image quality and optimize it only when you export image for consumption in web browsers.

**Comment by virginie24jb** [comment]
Thank you for your answer.
> However, I suggest that you change your workflow. Saving image as JPEG is lossy, so it should be the final step in any workflow, and such image should not be fed back into any image editing tools. If you want to keep images editable, keep them in PNG, RAW, or one of Adobe's formats. Degrade image quality and optimize it only when you export image for consumption in web browsers.


Don't worry, I don't edit JPG in Lightroom, just the Raw files. I noticed this bug as I imported the photos in an attempt to test different options of exports from Lightroom for the images I have on my website (in order to optimize them more). So that's a minor bug for me. It doesn't affect my general workflow.

**Comment by pornel** [comment]
I see. Sorry I don't have a better solution for this.
