### ISSUE TITLE
[Suggestion] - image resize

### ISSUE THREAD

**Issue by sp90** [ImageOptim/ImageOptim#178]
Maybe it would be nice to be able to resize images to the size you need, this is nice for web development atleast

**Comment by pathawks** [comment]
Automator can already do this easily :+1:

**Comment by pornel** [comment]
I've added resizing to the web API: https://imageoptim.com/api/post

but I'm not sure about adding it to the Mac app, because I don't know how to add it without complicating the UI.

**Comment by sp90** [comment]
This dosn't have to be a cropping tool, maybe just two  input fields on the top

To state width or height, and make the other one relative, and with that just throw stuff in and resize and then minify 👍

**Comment by curby** [comment]
I've started evaluating feature requests by the number of times someone uses the word "just."  As always, it's probably not as simple as you think, because any individual user cares mostly about their needs.  How do other programs handle resizing?

If you take recent versions of Lightroom as an example, their exporting UI has different options including a maximum dimension option.  Meaning if you set max=1000, large landscape images will be scaled to 1000px wide, portraits to 1000px tall.  Seems reasonable to me as you only need a single text field.  But what if you have a 800x600 image?  Should all images be scaled to 1000px on the largest dimension?  I imagine sometimes you might actually want that, though the default should be no.

**Comment by pathawks** [comment]
Often making images smaller involves sharpening the image a bit, or other adjustments. These are not “set it and forget it” the way losslessly rejiggering the bits is.

**Comment by pReya** [comment]
Why was this closed as "completed"? Is this already available in the Mac app?
