### ISSUE TITLE
Strip JPEG option not working

### ISSUE THREAD

**Issue by paleite** [ImageOptim/ImageOptim#209]
Hi!

I've unchecked the option "Strip JPEG metadata (EXIF, color profiles, GPS, rotation, etc.)", but the metadata is still being stripped, which causes problems when running in conjunction with JPEGmini and causes it to re-process already processed images in a lossy way.

I'm running version 1.7.0 on macOS 10.12.3.

Thanks in advance!

**Comment by pornel** [comment]
JPEGMini does not use EXIF data to detect its own files, so this option won't help anyway.

**Comment by paleite** [comment]
Thanks for clarifying. What is ImageOptim removing that prevents it from working?
Is there any way I could use ImageOptim even though I'm using JPEGmini?

**Comment by pornel** [comment]
I don't know what exactly JPEGMini does, but it could be using a database of file checksums (that's what ImageOptim does itself), which would mean any change at all would make the file appear as new again.

Because JPEGMini is lossy, I recommend keeping original unmodified files in some separate location, and only optimize copies of them.
