### ISSUE TITLE
SVGO CLI Options

### ISSUE THREAD

**Issue by thejamespower** [ImageOptim/ImageOptim#213]
Thanks for adding SVG support with SVGO! Much needed.

Do we have any scope to add the CLI options to the preferences panel? What options are currently passed to SVGO? Appreciate SVGO options are plugin based, so this may be quite tricky to implement. Happy to help if needed!

**Comment by pornel** [comment]
Which options do you find useful?

**Comment by thejamespower** [comment]
For me personally, --multipass, --pretty and --dataURI are the most useful options. For plugins its generally based on what I'm using the SVG for. If it's to be displayed in our UI/content as a static image, I usually have most of the plugins enabled. But for interactive SVGs (ones where we programmatically animate/interactive with the SVG DOM), we need to make sure plugins like mergePaths are disabled.

**Comment by pornel** [comment]
In ImageOptim these options are somewhat integrated with other ImageOptim options.

- plugins that could break interactive SVGs are disabled by default. They're enabled when you enable "Lossy" mode in quality settings.

- Copy as Data URL exists already. I forgot to enable it for SVG, so it will be fixed in the next version.

- multipass: I don't know what it does exactly. Is it just running SVGO multiple times? If so, the Again button might be a substitute.

- pretty - that makes files larger, so it's out of scope for ImageOptim.

**Comment by thejamespower** [comment]
Thanks for clarifying @pornel. Was not aware about 'lossy' mode for SVG, maybe would be nice to have something clarifying this in the Preferences dialogue?

As for multipass, yes it's supposed to continuously run optimisation/compression passes until the differences between each pass become incomprehensible. Also a shame about pretty, as this is extremely useful for developers who have to work with interactive SVGs, but we can just use SVGO CLI for this.
