### ISSUE TITLE
Commit changes

### ISSUE THREAD

**Issue by Wdavery** [ImageOptim/ImageOptim#273]
May fall out of the scope of the project, but I think it'd be a nice to have a "commit changes" option.
Obviously if you are worried about losing images you should make backups first but we all know how that goes.

An option in the preferences to create use a temp location for optimized images and then commit them  when finished. 

Would save people against issues with APNGs, and bad lossy settings.

**Comment by kornelski** [comment]
There's Revert option in the File menu (you can revert until you quit the app), and original files are put in Trash.

I should probably improve Revert by checking for files in Trash, so that it works even after restart. But apart from that I think the current behavior is fine. It's better to recover than to ask for permission.

**Comment by Wdavery** [comment]
I must have missed that option! Yes I think that behaviour works nicely then.
