### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by TomasSestak** [ImageOptim/ImageOptim#305]
Are you planning on supporting WebP?

**Comment by kornelski** [comment]
There are no plans. There's not much to optimize in WebP files, and there are no alternative implementations that I know of, so you should just use the latest version of the encoder.

**Comment by kornelski** [comment]
Browser are working on AVIF which is **half the size of WebP**, so when this comes out maybe I'll add AVIF.

**Comment by mathiasbynens** [comment]
> Browser are working on AVIF which is **half the size of WebP**, so when this comes out maybe I'll add AVIF.

This is happening now! What’s your current stance on adding AVIF support?

**Comment by kornelski** [comment]
I'm developing a bunch of AVIF tools:

https://github.com/kornelski/cavif/
https://lib.rs/avif-parse
https://lib.rs/avif-serialize

**Comment by mathiasbynens** [comment]
Does it make sense to optimize existing AVIF files (strip unnecessary metadata, if nothing else)?

**Comment by kornelski** [comment]
Maybe! I may have the first AVIF metadata optimizer already: https://github.com/kornelski/avif-serialize/blob/main/examples/optimize.rs

Buuut it sucks that the AVIF spec *requires* a lot of unnecessary bloat, and sadly Chrome enforces the spec. 

https://crbug.com/1120973

* I'm afraid that AVIF spec changes are nearly impossible, because it's based on HEIF/MIAF/BMFF, which are already ISO standards set in stone, and ISO seems to value compatibility with its own old specs and legacy video editing tools more than web-oriented use-cases.

* Supporting minimal metadata would require Chrome/libavif to willfully break "shall" parts of the specs.

**Comment by mathiasbynens** [comment]
> Maybe! I may have the first AVIF metadata optimizer already: https://github.com/kornelski/avif-serialize/blob/main/examples/optimize.rs

Awesome! Do you think it’d make sense to include this in ImageOptim.app? Even if it only strips a minimum amount of metadata for now, we can always make it more eager in the future depending on how the Chrome metadata situation evolves.

**Comment by mathiasbynens** [comment]
Apologies for pinging this issue. @kornelski do you have an opinion re: [the above](https://github.com/ImageOptim/ImageOptim/issues/305#issuecomment-683262598)?
