### ISSUE TITLE
Optimising WebP images

### ISSUE THREAD

**Issue by custa1200** [ImageOptim/ImageOptim#338]
It would be good to optimise WebP images, i.e using Lossy

**Comment by Allmedialab** [comment]
webp is supported by all current browsers and AVIF not, despite the fact that you can save more bandwidth and preserve better quality images with AVIF.
https://w3techs.com/technologies/details/im-webp#:~:text=WebP%20is%20used%20by%201.3%25%20of%20all%20the%20websites.

There are multiple lossless webp optiimizers like the one on this image.

![webp](https://user-images.githubusercontent.com/2815617/113154205-0f73c000-9238-11eb-96a7-faddb271740d.png)

**Comment by kornelski** [comment]
The tool you mention uses `libwebp`, which as far as I can tell, is the only implementation of WebP in existence. This effectively makes all WebP-related tools *identical*. They all do the same things using the same library. 

Optimization is about replacing an old library with a newer one. WebP has no better implementation.

**Comment by custa1200** [comment]
Apple as part of 11.3 have only just supported WebP at the system level which I would suggest doesn't make it obsolete. Another platform I work with being Roku has also only just recently added WebP as an option in either 9.3 or 9.4 of their OS. With the max app size of Roku being 4MB, any reductions are highly sought after on that platform.

**Comment by custa1200** [comment]
Another reason why it would be handy for the WebP library to be in ImageOptim would be I use it as a one stop shop with exporting items from Sketch at 100% quality and then set all the image settings I want to use within ImageOptim as the one stop shop. I also do wonder if having WebP in ImageOptim also has the latest version which I'm not sure but could potentially be more up to date that something like Sketch includes. I did a quick test online and even using a lossy WebP at 99% quality I still saw a ~50% reduction in file size for non alpha WebP's and ~20% for alpha channeled

**Comment by NiklasBr** [comment]
@custa1200 what do you expect the end result would be if `libwebp` was added to ImageOptim? Saving a WebP image using the same algo/library again would not improve file size and it would therefore be useless in the context of an optimizer application.

**Comment by kornelski** [comment]
Exactly, if I added libwebp to ImageOptim, you'd get just the green X "nothing to do, 0 bytes saved" case for every WebP image, because nobody has written any other implementation of the encoder. 

It could recompress lossy WebP to lower quality, but the **VP8 codec is *extraordinarily* bad** for this due to its aggressive in-loop deblocking that blurs things away every time the file is resaved. It reduces the file size, but only by losing more in quality than it should (see the generation loss example below). I consider that a crappy cheat, and I'll leave such bad ideas to other tools that call themselves optimizers, because that's not a real optimization.

[![generationloss](https://user-images.githubusercontent.com/72159/116991523-93541880-accc-11eb-8ab2-39e416aeb658.jpg)](https://www.youtube.com/watch?v=w7UDJUCMTng)

If someone wrote an alternative WebP encoder, I could use it, but so far it's just Google's format with Google's implementation.

The real innovation in formats is happening with AVIF and JPEG XL these days. AVIF actually has multiple implementations now, and I could create an optimizer for it! In this aspect it's already a more mature format, and actually qualifies to be a W3C web standard (unlike WebP, which has Web only because Google unilaterally chose to name it like this, but has nothing to do with any Web standard).
