### ISSUE TITLE
1.8.8 does not run on Ventura

### ISSUE THREAD

**Issue by dmurko** [ImageOptim/ImageOptim#397]
Version:
<img width="271" alt="Screenshot 2022-10-25 at 16 07 26" src="https://user-images.githubusercontent.com/1309671/197796045-97c91861-1131-424a-87b6-22f44af8ce40.png">

Error:
<img width="274" alt="Screenshot 2022-10-25 at 16 08 08" src="https://user-images.githubusercontent.com/1309671/197796076-8dba6ee1-f156-4a7f-8ffd-4a4a62cc285c.png">

**Comment by kornelski** [comment]
It runs for me on Ventura 13.0 (22A380), but it might be because I've run it previously?

Unfortunately, I don't have any fix for this. macOS now requires Apple's approval for running 3rd party software (Apple calls it "Notarization"), and due to Xcode bug FB9885692 I'm unable to submit any new builds of ImageOptim for approval.

**Comment by dmurko** [comment]
Ah, I see, I've also changed to M2 Mac in this time, so I'm assuming that.

I'll close this issue.
