### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by cachius** [ImageOptim/ImageOptim#414]
It would be really handy to have clipboard support. 📋

I take a lot of screenshots to paste directly into various messengers. The default PNG encoding of macOS is so bloated 🎈 that often more than half can be shaved off 🪒 using ImageOptim at 60% quality with OxiPNG.

Unfortunately, the manual file-based approach of _taking the screenshot to a file, dragging it into ImageOptim and then copying it to the clipboard_ is too cumbersome in practice. Thus all those reduntant bytes are getting sent, clogging up disk space on both sides forever.

It would be great if ImageOptim could detect when a screenshot is taken to the clipboard and optimize it on the fly. 🖼️🪄

**Comment by MikeRich88** [comment]
Even if you manage to optimize the clipboard PNG, you would then have to make sure that the messenger app doesn't recompress it again for whatever reason (which would make it larger again).

I have observed Messages.app on macOS recompressing PNGs, converting PNGs to JPEGs, and every once in a while, it will decide to send an uncompressed (!!!) TIFF in the message. (this might be because I pasted an image and the clipboard only had a TIFF version for some reason, but I have not been able to reproduce consistently).

**Comment by cachius** [comment]
> when a screenshot is taken to the clipboard optimize it on the fly

I found [Clop](https://lowtechguys.com/clop/) doing exactly this.
It also has a folder watcher mode in the Pro version.
Repo is over at https://github.com/FuzzyIdeas/Clop

**Comment by cachius** [comment]
And for reference, [ShareX ](https://getsharex.com/) as quite sophisticated Windows alternative, [repo](/ShareX/ShareX).
You have to set up compression as an [Action](https://getsharex.com/actions) after capture. Example [here](/ShareX/ShareX/issues/4268#issuecomment-564315909).
