### ISSUE TITLE
Optimise HEIC

### ISSUE THREAD

**Issue by MattiSG** [ImageOptim/ImageOptim#433]
Hi and thank you so much for maintaining ImageOptim!

I read in https://github.com/ImageOptim/ImageOptim/issues/332#issuecomment-745470493 that HEIC is considered as problematic due to HEVC licensing.

I also see that some [other](https://www.widsmob.com/heic) [tools](https://www.xconvert.com) claim to compress HEIC further (based on my limiting testing, they fail).

I open this issue to have a consolidated place to discuss adding HEIC support to the list of formats handled by ImageOptim, and to potentially clarify the precise licensing issues and potential workarounds, such as a plugin system like `ffmpeg` does with `libx265` 🙂

**Comment by kornelski** [comment]
Nothing has changed in terms of licensing. 

Please be aware that licensing of patents is separate from licensing of copyright. 

Patents apply to everything. Patent owners own any expression of that patent, made by anyone, anywhere.

If you close yourself in a room, invent an image format completely yourself, write all the code yourself based on your own idea, but it happens to be similar to HEIC, your work will be owned by HEIC owners and you will have to pay them for daring to have thought about the same thing.

So I can't use libx265, because it gives me a copyright license, but they don't own the patents and can't give them to me. Patent owners can go after anybody using libx265 who haven't bought a patent license for the free software written by someone else.

Software patents are horrible. They're terribly unfair. They are a cancer on the industry. 

I do not plan to ever support HEIC and urge everyone to treat this format as toxic.

**Comment by ylluminate** [comment]
Sadly this is being forced upon us more and more and many of us cannot get away from it. It appears it is not going to go away in neither short nor long term... <sigh> I think we will have to have options that consider it even though patents are a major curse of our present society. <quadruple sigh>

Might it be possible to use this LGPL'd project to fill in this need?: https://github.com/libvips/libvips

**Comment by Sea-Worker9552** [comment]
How does Clop do HEIC? By default I believe they just convert to JPEG.

**Comment by kornelski** [comment]
There are two ways to use HEIC currently:

1. Reuse Apple's codec that the user has already paid for when buying the Mac.

2. Ignore patent licensing, potentially break the law, and hope nobody cares.

The first option does not allow to optimize anything, because you can't beat Apple's codec by using the very same Apple's codec.

The second option is a popular one among projects not worth suing. I don't want to get into it.

**Comment by Sea-Worker9552** [comment]
Got it. What about zero optimization but at least removing EXIF? I use this tool mainly for the EXIF stripping capabilities as many images out of modern smartphones are already well compressed.

**Comment by ylluminate** [comment]
Very good point from @Sea-Worker9552. Furthermore I think the idea would also be to be able to move heic → jpeg/png as appropriate (even though it is less compressed) if set to do so... and as heic becomes more openly supported (I suspect this will happen), then the reverse could be true.

And of course exif and other metadata stripping is important in either direction.

**Comment by Sea-Worker9552** [comment]
Maybe that's how Clop does it actually without violating any licensing issues is convert to JPG then compress. But I'm not well versed in the HEIC format itself.
