### ISSUE TITLE
Support lossless compression of BMP and TIFF

### ISSUE THREAD

**Issue by fulldecent** [ImageOptim/ImageOptim#48]
Per title

**Comment by deanmoses** [comment]
I use TIFFs as lossless, editable image files.  They contain all my metadata like locations and keywords.  Mostly they're produced by my scanner.  Unfortunately the programs that hook up to my scanner produce uncompressed TIFFs.

I'd like to drop a folder of uncompressed TIFFs onto ImageOptim and have them become losslessly compressed TIFFs, and preserve all metadata, with my choice of either LZW or ZIP.  I use LZW mostly because all my image editing tools support it, whereas support for ZIP is still spotty (on mac at least).

**Comment by fulldecent** [comment]
The reason I am recommending this feature is because ImageOptim fits into my workflow as:

1. Prepare website or iOS app
2. Run ImageOptim
3. Publish
4. Be at ease because all metadata is gone

**Comment by tobsen** [comment]
I export a lot of icons from Sketch, which only writes uncompressed Tiff. Since I use the ImageOptim Plugin, it would be nice if it simply recompresses the Tiff with ZIP or LZW.

At the moment I use Hazel to automatically run ImageMagick's convert command on the files. E.g. a 1.4MB Icon will be compressed to 4KB to 700KB with LZW.
